encoding: UTF-8

url: "https://blog.awardfares.com"
title: AwardFares Blog
description: News, Tips, Reviews, and Trip Reports

search: false

paginate: 10
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed

permalink: /:slug/

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  
exclude:
  - .git/
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - serve.sh
  - node_modules
  - package.json
  - yarn.lock
  